#!/usr/bin/env bash
# Creates the ntfy users, ACLs and publish token for the clawlight topic.
#
# ntfy has no web UI for user management (the known friction point noted in
# PROJECTS.md), so this is the CLI equivalent, made idempotent and repeatable
# rather than a one-off session of docker exec commands.
#
# Two principals, deliberately split so a leaked publisher token cannot read
# your notification history:
#   pramod    - read-write on the topic. This is what the phone app logs in as.
#   clawlight - write-only, used via a token rather than a password. This is
#               what clawlight/server.py publishes with.
#
# NOTE on the -e flags below: `docker exec` does NOT forward the host's
# environment into the container, so NTFY_PASSWORD has to be handed over
# explicitly. Setting it only on the host side leaves ntfy prompting for a
# password on stdin and the script hangs.
#
# Secrets are written to .env.ntfy (gitignored, mode 600). Re-running reuses the
# credentials already in that file rather than churning them, so it is safe to
# run repeatedly.
set -euo pipefail
cd "$(dirname "$0")/.."

ENVFILE=".env.ntfy"
TOPIC="clawlight"

nt() { docker exec -i ntfy ntfy "$@" </dev/null; }

docker ps --format '{{.Names}}' | grep -qx ntfy || { echo "ntfy container is not running" >&2; exit 1; }

# shellcheck disable=SC1090
[ -f "$ENVFILE" ] && . "$ENVFILE"

GENERATED_PASSWORD=0
if [ -z "${NTFY_ADMIN_PASSWORD:-}" ]; then
  NTFY_ADMIN_PASSWORD="$(head -c 24 /dev/urandom | base64 | tr -d '/+=' | head -c 24)"
  GENERATED_PASSWORD=1
  echo "generated a new password for user 'pramod'"
fi

# --- users (--ignore-exists makes these no-ops on re-run) -------------------
docker exec -i -e NTFY_PASSWORD="$NTFY_ADMIN_PASSWORD" ntfy \
  ntfy user add --ignore-exists pramod </dev/null

# The clawlight account authenticates by token only, so its password is a
# throwaway that is generated and immediately discarded.
docker exec -i -e NTFY_PASSWORD="$(head -c 32 /dev/urandom | base64)" ntfy \
  ntfy user add --ignore-exists clawlight </dev/null

# If we generated a password this run but the user already existed (e.g. a
# previous run created the account and then failed before writing .env.ntfy),
# the stored password and the one we are about to record would disagree. There
# is no way to read the old one back, so force it to match what gets written.
if [ "$GENERATED_PASSWORD" = 1 ]; then
  docker exec -i -e NTFY_PASSWORD="$NTFY_ADMIN_PASSWORD" ntfy \
    ntfy user change-pass pramod </dev/null
fi

# --- ACLs (ntfy access overwrites the rule for that user+topic, so idempotent) --
nt access pramod    "$TOPIC" rw
nt access clawlight "$TOPIC" write-only

# --- publish token ----------------------------------------------------------
if [ -z "${NTFY_CLAWLIGHT_TOKEN:-}" ]; then
  # No --expires flag at all is the never-expiring form ("--expires=never" is
  # not a thing - it fails with "unable to parse duration"). The token inherits
  # the clawlight user's permissions, so it stays write-only.
  NTFY_CLAWLIGHT_TOKEN="$(nt token add --label='clawlight publisher' clawlight \
                          | grep -oE 'tk_[A-Za-z0-9]+' | head -1)"
  [ -n "$NTFY_CLAWLIGHT_TOKEN" ] || { echo "failed to create publish token" >&2; exit 1; }
  echo "created publish token for user 'clawlight'"
fi

# Tapping the notification should open the clawlight page. Kept here rather
# than in the committed systemd unit so the tailnet name stays out of git,
# same reasoning as the Caddyfile's {$TAILNET_SUFFIX}.
if [ -z "${CLAWLIGHT_PUBLIC_URL:-}" ]; then
  # shellcheck disable=SC1091
  [ -f .env ] && . ./.env
  CLAWLIGHT_PUBLIC_URL="https://xero.${TAILNET_SUFFIX}/clawlight/"
fi

umask 077
cat > "$ENVFILE" <<ENVEOF
# ntfy credentials - generated by scripts/setup_ntfy_users.sh. Gitignored.
# Loaded by clawlight-server.service via EnvironmentFile.
# NTFY_ADMIN_PASSWORD  : log in as user 'pramod' in the mobile app / web UI.
# NTFY_CLAWLIGHT_TOKEN : write-only publish token used by clawlight/server.py.
# CLAWLIGHT_PUBLIC_URL : where tapping the notification takes you.
NTFY_ADMIN_PASSWORD=$NTFY_ADMIN_PASSWORD
NTFY_CLAWLIGHT_TOKEN=$NTFY_CLAWLIGHT_TOKEN
CLAWLIGHT_PUBLIC_URL=$CLAWLIGHT_PUBLIC_URL
ENVEOF
chmod 600 "$ENVFILE"

echo
echo "--- users and ACLs ---"
nt access
echo
echo "credentials written to $ENVFILE (mode 600)"
