#!/usr/bin/env bash
# One-shot install for the DNS recorder. RUN THIS ON THE MAC.
#
#   scp <user>@xero:/home/pramod/code/homelab/scripts/setup-mac-dns-recorder.sh /tmp/
#   bash /tmp/setup-mac-dns-recorder.sh --dry-run
#   bash /tmp/setup-mac-dns-recorder.sh
#
# The Mac's copies of these scripts are scp'd, not a git clone, so a commit on
# xero does nothing here until this is re-run. Re-running is the update path.
#
# Overrides: XERO_SSH (default $USER@xero), XERO_REPO, DEST.
set -u

REPO="${XERO_REPO:-/home/pramod/code/homelab}"
XERO="${XERO_SSH:-$USER@xero}"
DEST="${DEST:-$HOME/code/personal/scripts}"
PLIST="$HOME/Library/LaunchAgents/dev.homelab.dns-recorder.plist"
LABEL="dev.homelab.dns-recorder"
STATE_DIR="$HOME/Library/Logs/homelab/dns-recorder"
ERRLOG="$STATE_DIR/dns-recorder.err"

dry_run=0
[ "${1:-}" = "--dry-run" ] && dry_run=1

die() { printf 'error: %s\n' "$*" >&2; exit 1; }
say() { printf '%s\n' "$*"; }
run() { if [ "$dry_run" = 1 ]; then printf '  would run: %s\n' "$*"; else "$@"; fi; }

[ "$(uname)" = "Darwin" ] || die "this installs a launchd agent; run it on the Mac"

say "pulling from:  $XERO:$REPO   (override with XERO_SSH=)"
say "installing to: $DEST"
say "recording to:  $STATE_DIR"
say

run mkdir -p "$DEST" "$STATE_DIR"
run scp "$XERO:$REPO/scripts/mac-dns-recorder.sh" "$DEST/mac-dns-recorder.sh"
# Refresh the diagnostic too - the stale copy on this Mac is what sent the
# 2026-09-10 investigation down the wrong path, by silently omitting the
# Setup-vs-State section that names who owns a bad resolver.
run scp "$XERO:$REPO/scripts/diagnose_macbook_dns.sh" "$DEST/diagnose_macbook_dns.sh"
run scp "$XERO:$REPO/scripts/fix_macbook_dns.sh" "$DEST/fix_macbook_dns.sh"
run chmod +x "$DEST/mac-dns-recorder.sh" "$DEST/diagnose_macbook_dns.sh" "$DEST/fix_macbook_dns.sh"

say
say "writing $PLIST"
if [ "$dry_run" = 1 ]; then
  say "  would write it pointing at $DEST/mac-dns-recorder.sh"
else
  mkdir -p "$(dirname "$PLIST")"
  cat > "$PLIST" <<PLIST_EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<!-- Generated by scripts/setup-mac-dns-recorder.sh - re-run it rather than
     hand-editing, so this cannot drift from the script it launches. -->
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>$LABEL</string>
  <key>ProgramArguments</key>
  <array>
    <string>$DEST/mac-dns-recorder.sh</string>
  </array>
  <key>EnvironmentVariables</key>
  <dict>
    <!-- launchd hands out a minimal PATH, and every tool this needs
         (scutil, networksetup, ipconfig, route, ping) lives in /usr/sbin
         or /sbin. The script also addresses them absolutely. -->
    <key>PATH</key>
    <string>/usr/bin:/bin:/usr/sbin:/sbin</string>
  </dict>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <true/>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardErrorPath</key>
  <string>$ERRLOG</string>
</dict>
</plist>
PLIST_EOF
  plutil -lint "$PLIST" >/dev/null || die "generated plist is malformed"
fi

say "loading the agent"
run launchctl unload "$PLIST" 2>/dev/null
run launchctl load "$PLIST"

[ "$dry_run" = 1 ] && { say; say "dry run - nothing changed"; exit 0; }

# --- verify it is actually recording, rather than assuming ------------------
say
say "waiting for the first poll to complete..."
ok=0
for _ in 1 2 3 4 5 6 7 8 9 10; do
  sleep 2
  [ -f "$STATE_DIR/.last-poll" ] && { ok=1; break; }
done

if [ "$ok" = 1 ]; then
  say
  "$DEST/mac-dns-recorder.sh" --show 1
  say
  say "Installed. It now snapshots on every resolver change."
  say
  say "Next time DNS breaks on this Mac, run this BEFORE fixing anything:"
  say "    $DEST/mac-dns-recorder.sh --timeline"
  say "and the change that broke it, plus who owned the setting, is already there."
else
  say "the agent did not complete a poll - check $ERRLOG"
  tail -20 "$ERRLOG" 2>/dev/null
  exit 1
fi
